void ls(unsigned int client_cmd_port, int client_cmd_socket);
void lls();
void get(struct command* cmd, int client_cmd_socket, unsigned int client_cmd_port);
void put(struct command* cmd, int client_cmd_socket, unsigned int client_cmd_port);
void cd(struct command* cmd);
void lcd(struct command* cmd);
void pwd(struct command* cmd);
void lpwd(struct command* cmd);
void ascii();
void binary();
void delete_cmd(struct command* cmd);
void mkdir(struct command* cmd);
void open_cmd(struct command* cmd, int client_cmd_socket);
void help();
void exit_cmd();